# version: "3.9"
# services:
#   ldap:
#     image: dcm4che/slapd-dcm4chee:2.6.3-29.0
#     logging:
#       driver: json-file
#       options:
#         max-size: "10m"
#     ports:
#       - "389:389"
#     env_file: docker-compose.env
#     volumes:
#       - ./data/pacs/ldap:/var/lib/ldap
#       - ./data/pacs/slapd.d:/etc/ldap/slapd.d
#   db:
#     image: dcm4che/postgres-dcm4chee:14.5-29
#     logging:
#       driver: json-file
#       options:
#         max-size: "10m"
#     ports:
#       - "5432:5432"
#     env_file: docker-compose.env
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - ./data/pacs/db:/var/lib/postgresql/data
#   arc:
#     image: dcm4che/dcm4chee-arc-psql:5.29.0
#     logging:
#       driver: json-file
#       options:
#         max-size: "10m"
#     ports:
#       - "8080:8080"
#       - "8443:8443"
#       - "9990:9990"
#       - "9993:9993"
#       - "11112:11112"
#       - "2762:2762"
#       - "2575:2575"
#       - "12575:12575"
#     env_file: docker-compose.env
#     environment:
#       WILDFLY_CHOWN: /opt/wildfly/standalone /storage
#       WILDFLY_WAIT_FOR: ldap:389 db:5432
#     depends_on:
#       - ldap
#       - db
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - ./data/pacs/wildfly:/opt/wildfly/standalone
#       - ./data/pacs/storage:/storage

version: "3.9"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.3-29.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - ./data/pacs/ldap:/var/lib/ldap
      - ./data/pacs/slapd.d:/etc/ldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:14.5-29
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5433:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/pacs/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.29.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/pacs/wildfly:/opt/wildfly/standalone
      - ./data/pacs/storage:/storage
  db-backend:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s
    env_file: ./backend/docker-compose.env
    volumes:
      - db-data-backend:/var/lib/postgresql/data
      - ./backend/initdb.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/src/.env
    ports:
      - "8000:8000"
    depends_on:
      db-backend:
        condition: service_healthy
    volumes:
      - ./backend/src/app:/code/app

volumes:
  db-data-backend:
